name: Deploy tt-fe to GitHub Pages
on:
  workflow_dispatch: # Manual trigger only
permissions:
  contents: write # Allow pushing to gh-pages branch
concurrency:
  group: pages # Prevent parallel Pages deployments
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build tt-fe
        run: npx nx build tt-fe --configuration=production --base-href=/tt-fe/

      - name: Add 404 fallback for SPA routes
        run: cp dist/apps/tt-fe/index.html dist/apps/tt-fe/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/apps/tt-fe
          keep_files: true
