name: Deploy ssm to GitHub Pages
on:
  workflow_dispatch: # Manual trigger only
permissions:
  contents: write
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build ssm
        run: npx nx build ssm --configuration=production --base-href=/nx-monorepo/ssm/

      - name: Debug build output
        run: ls -la dist/apps/ssm/browser

      - name: Add 404 fallback for SPA routes
        run: |
          if [ -f "dist/apps/ssm/browser/index.html" ]; then
            cp dist/apps/ssm/browser/index.html dist/apps/ssm/browser/404.html
          else
            echo "⚠️ Warning: index.html not found! Skipping 404.html copy."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/apps/ssm/browser
          keep_files: true
